### PR TITLE
Update tungstenite to 0.20.1 for security update

### PR DESCRIPTION
**Pull request by jhg**
Crate:         tungstenite
Version:       0.16.0
Title:         Tungstenite allows remote attackers to cause a denial of service
Date:          2023-09-25
ID:            RUSTSEC-2023-0065
URL:           https://rustsec.org/advisories/RUSTSEC-2023-0065
Solution:      Upgrade to >=0.20.1

### CODE REVIEW

**Comment by jhg** [comment]
I see now the `Cargo.lock` file, I'll update that to fix the error in the workflow.

**Comment by lemunozm** [comment]
Thanks a lot for your contribution!

**Comment by jhg** [comment]
Excuse me to late, it's done now. The `Cargo.lock` file is updated and it'll use tungstenite 0.21.0, the check and test show only warnings but without errors.

@lemunozm is there an estimated date for next release?

**Comment by lemunozm** [comment]
Thanks for fixing it! I'll try this week

**Comment by lemunozm** [comment]
This change is in `v0.18.1`

**Pull request merged**
