### PR TITLE
Removed race condition by joining create and cancel timer queues.

### PR DESCRIPTION
**Pull request by garin1000**
Hi Luis,
this should solve issue #136.
Best,
Garin

### CODE REVIEW

**Review by lemunozm — CHANGES_REQUESTED** [review]
Thanks @garin1000! Pretty clean change 😃. Only a couple of things:

- We need to remove the `eprint` lines because it can reduce the performace and generate unexpected output in applications. 
- I think there is some line that `cargo fmt` will complain about.

Fixing these two things I'll merge it. Thanks too for changing the version number!

**Comment by garin1000** [comment]
Um, I ja then in for my debugging, but I thought I caught them all. It wasn't really intended to have them in the PR.

**Comment by garin1000** [comment]
Hi Luis, removed the eprintln!() and changed formatting.

**Review by lemunozm — APPROVED** [review]

**Comment by lemunozm** [comment]
Nice! Thanks for your contribution @garin1000!

**Comment by garin1000** [comment]
Happy to help!

**Pull request merged**
